version: "3"

services:
  app:
    container_name: server
    restart: always
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/src/:/app/src/
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:3000
      - SPOTIFY_PUBLIC=__your_spotify_client_id__
      - SPOTIFY_SECRET=__your_spotify_secret__
      - CORS=all
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432

  web:
    container_name: web
    restart: always
    build:
      context: ./client
      args:
        - ENVIRONMENT=DEV
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src/
      - ./client/public:/app/public/
    environment:
      - API_ENDPOINT=http://localhost:8080
    entrypoint: "/app/scripts/run/run_dev.sh"
